name: JetBrains-953
env:
  APPLICATION_NAME : "JetBrains-953"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: Java version
        run: java -version
      - name: Installing maven
        run: sudo apt-get -y install maven
      - name: Maven version
        run: mvn -version
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Run tests
        env:
          TESTING_REPOSITORY_BRANCH: ${{ secrets.TESTING_REPOSITORY_BRANCH }}
          TESTING_REPOSITORY_NAME: ${{ secrets.TESTING_REPOSITORY_NAME }}
          TESTING_REPOSITORY_OWNER: ${{ secrets.TESTING_REPOSITORY_OWNER   }}
          TESTING_REPOSITORY_TOKEN: ${{ secrets.TESTING_REPOSITORY_TOKEN }}
        run: mvn test
